exp_root_dir: "outputs"
name: "DragDec"
tag: "test"
seed: 0

system:
  shape_model_type: "michelangelo-autoencoder"
  shape_model:
    pretrained_model_name_or_path: outputs/ShapeVAE/shapevae_output/ckpts/last.ckpt
    embed_dim: 64
    point_feats: 3
    out_dim: 1 
    embed_type: "fourier"
    num_freqs: 8
    include_pi: false
    heads: 12
    width: 768
    num_encoder_layers: 8
    num_decoder_layers: 16
    use_ln_post: true
    init_scale: 0.25
    qkv_bias: false
    use_flash: true
    use_checkpoint: true
    use_downsample: true

  drag_model:
    pretrained_model_name_or_path: outputs/DragDec/dragdec_output/ckpts/last.ckpt
    sample_posterior: false
    embed_dim: 64
    point_feats: 3
    out_dim: 1 
    embed_type: "fourier"
    num_freqs: 8
    include_pi: false
    heads: 12
    width: 768
    num_latents: 256
    num_encoder_layers: 8
    num_decoder_layers: 3
    use_ln_post: true
    init_scale: 0.25
    qkv_bias: false
    use_flash: true
    use_checkpoint: true
    use_downsample: true

    DRAG_MEAN: 0.0
    DRAG_STD: 1.0

data:
  data_root: "data/drivaernet_plus/surfaces"
  csv_path: "data/drivaernet_plus/drag/DrivAerNetPlusPlus_Cd_8k_Updated.csv"
  root_dir: "./data/dataset1"
  data_type: "sdf"

  batch_size: 64
  num_workers: 8

trainer:
  num_nodes: 1
  max_epochs: 1
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  enable_progress_bar: true
  precision: 16-mixed
